services:
  caddy:
    image: ghcr.io/quentinreytinas/caddy-ovh:latest
    container_name: caddy-ovh
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT:-ovh-eu}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 5s
      retries: 3


  watchtower:
    image: containrrr/watchtower:latest
    container_name: caddy-ovh-watchtower
    command: --interval 21600 --label-enable --cleanup caddy-ovh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
